### ISSUE TITLE
Error in running the scala web app

### ISSUE THREAD

**Issue by NitishDeshpande** [vert-x/vertx-examples#28]
I am getting this problem when running the scala webapp,

C:\Users\XXXXX\Desktop\Vertx\vertx-examples-master\vertx-examples-master\src\modules\scala\webapp> vertx runmod io.vertx~example-web-app~1.0
...
Failed in deploying module
java.lang.IllegalArgumentException: Unable to compile C:\Users\XXXXX\Desktop\Vertx\vertx-examples-master\vertx-examples-master\src\modules\scala\webapp\mods\io.vertx~example-web-app~1.0\app.scala
        at org.vertx.scala.lang.ScalaInterpreter.compileClass(ScalaInterpreter.scala:93)
        at org.vertx.scala.platform.impl.ScalaVerticleFactory$$anonfun$load$1.applyOrElse(ScalaVerticleFactory.scala:107)
        at org.vertx.scala.platform.impl.ScalaVerticleFactory$$anonfun$load$1.applyOrElse(ScalaVerticleFactory.scala:98)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
        at scala.util.Failure.recoverWith(Try.scala:172)
        at org.vertx.scala.platform.impl.ScalaVerticleFactory.load(ScalaVerticleFactory.scala:98)
        at org.vertx.scala.platform.impl.ScalaVerticleFactory.createVerticle(ScalaVerticleFactory.scala:70)
        at org.vertx.java.platform.impl.DefaultPlatformManager$21.run(DefaultPlatformManager.java:1748)
        at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at java.lang.Thread.run(Thread.java:744)

**Comment by galderz** [comment]
What vert.x version are you running this with? Also, can you try running it with `-Dvertx.scala.interpreter.verbose=true` and paste the output?
